"""
Report generation for the classification module.

Compiles all results into an HTML report with embedded figures
and a JSON summary document.
"""
from __future__ import annotations

import base64
from pathlib import Path
from typing import Any, Dict

import numpy as np
import pandas as pd
from jinja2 import Template

from classification.src.utils import write_json


# ------------------------------------------------------------------ #
#  HTML report                                                       #
# ------------------------------------------------------------------ #

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ title }}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
  h1 { color: #1565C0; border-bottom: 2px solid #1565C0; padding-bottom: 10px; }
  h2 { color: #1976D2; margin-top: 40px; }
  h3 { color: #1E88E5; }
  table { border-collapse: collapse; width: 100%; margin: 15px 0; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  th { background-color: #E3F2FD; font-weight: 600; }
  tr:nth-child(even) { background-color: #f9f9f9; }
  .metric-good { color: #2E7D32; font-weight: bold; }
  .metric-bad { color: #C62828; }
  .note { background: #FFF3E0; padding: 12px; border-left: 4px solid #FF9800; margin: 15px 0; }
  .warning { background: #FFEBEE; padding: 12px; border-left: 4px solid #F44336; margin: 15px 0; }
  .figure { text-align: center; margin: 20px 0; }
  .figure img { max-width: 100%; border: 1px solid #ddd; border-radius: 4px; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #777; font-size: 0.9em; }
</style>
</head>
<body>

<h1>{{ title }}</h1>
<p><strong>Author:</strong> {{ author }} | <strong>Primary metric:</strong> {{ primary_metric }}</p>

<h2>1. Data Overview</h2>
<ul>
  <li>Samples: {{ n_samples }}</li>
  <li>Features (primary experiment): {{ n_features_primary }}</li>
  <li>Classes: {{ class_labels | join(', ') }}</li>
  <li>Class distribution: {{ class_dist_str }}</li>
</ul>

<h2>2. Feature Leakage Analysis</h2>
<div class="warning">
  <strong>Warning:</strong> Target (shrinkage_class) is derived from elderly_ratio thresholds.
  Features <code>elderly_ratio</code>, <code>aging_index</code>, <code>youth_ratio</code>
  are deterministic functions of the target and constitute data leakage.
</div>
<p>Primary experiment: <strong>{{ primary_experiment }}</strong> ({{ n_features_primary }} features)</p>
<table>
  <tr><th>Experiment</th><th>Features</th><th>Description</th></tr>
  {% for exp in experiments %}
  <tr><td>{{ exp.name }}</td><td>{{ exp.n_features }}</td><td>{{ exp.description }}</td></tr>
  {% endfor %}
</table>

{% if figures.leakage_comparison %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.leakage_comparison }}" alt="Leakage comparison">
</div>
{% endif %}

<h2>3. Model Comparison</h2>
{{ comparison_table_html }}

{% if figures.model_comparison %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.model_comparison }}" alt="Model comparison">
</div>
{% endif %}

{% if figures.cv_boxplots %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.cv_boxplots }}" alt="CV boxplots">
</div>
{% endif %}

<h2>4. Best Model: {{ best_model_name }}</h2>
<p>{{ best_model_metrics_str }}</p>

{% if figures.roc_curves %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.roc_curves }}" alt="ROC curves">
</div>
{% endif %}

{% if figures.best_confusion_matrix %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.best_confusion_matrix }}" alt="Confusion matrix">
</div>
{% endif %}

<h2>5. Feature Importance</h2>

{% if figures.permutation_importance %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.permutation_importance }}" alt="Permutation importance">
</div>
{% endif %}

{% if figures.shap_summary %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.shap_summary }}" alt="SHAP summary">
</div>
{% endif %}

<h2>6. Statistical Tests</h2>
<p><strong>Friedman test:</strong> χ²={{ friedman_stat }}, p={{ friedman_p }}</p>
{% if significant_findings %}
<ul>
  {% for finding in significant_findings %}
  <li>{{ finding }}</li>
  {% endfor %}
</ul>
{% endif %}

<h2>7. PCA Diagnostics</h2>
{% if figures.pca_variance %}
<div class="figure">
  <img src="data:image/png;base64,{{ figures.pca_variance }}" alt="PCA variance">
</div>
{% endif %}
<p>Components for 95% variance: {{ n_components_95 }}</p>

<div class="footer">
  <p>Generated by the classification pipeline. All results based on
  {{ n_splits }}×{{ n_repeats }} Repeated Stratified K-Fold CV.</p>
</div>

</body>
</html>
"""


def generate_report(summary: Dict[str, Any], cfg: Dict[str, Any]) -> None:
    """
    Generate HTML report and JSON summary.

    Args:
        summary: Collected results from all pipeline steps.
        cfg:     Configuration dict.
    """
    if not cfg["report"].get("generate_html", True):
        print("HTML report generation disabled.")
        _save_json_summary(summary, cfg)
        return

    print("Generating HTML report ...")
    figures_dir = Path(cfg["output"]["figures_dir"])

    # Embed figures as base64
    figure_map: Dict[str, str] = {}
    figure_files = {
        "model_comparison": "model_comparison.png",
        "cv_boxplots": "cv_boxplots.png",
        "roc_curves": "roc_curves_best.png",
        "permutation_importance": "permutation_importance.png",
        "shap_summary": "shap_summary.png",
        "leakage_comparison": "leakage_comparison.png",
        "pca_variance": "pca_variance.png",
    }
    best_name = summary.get("best_model_name", "")
    if best_name:
        figure_files["best_confusion_matrix"] = f"confusion_matrix_{best_name}.png"

    for key, fname in figure_files.items():
        fpath = figures_dir / fname
        if fpath.exists():
            figure_map[key] = _encode_image(fpath)

    # Build comparison table HTML
    comp_table = summary.get("comparison_table")
    if comp_table is not None:
        display_cols = ["display_name"] + cfg["evaluation"]["metrics"]
        existing = [c for c in display_cols if c in comp_table.columns]
        table_html = comp_table[existing].to_html(
            index=False, float_format="%.3f", classes="",
        )
    else:
        table_html = "<p>No comparison table available.</p>"

    # Experiment info
    experiments_info = []
    exp_descriptions = {
        "all_features": "All 30 features (reference — includes leaky features)",
        "no_leaky": "Drops elderly_ratio, aging_index, youth_ratio (PRIMARY)",
        "no_demographic": "Drops all demographic features",
        "rs_only": "Remote sensing features only",
    }
    for exp_name, n_feat in summary.get("experiment_feature_counts", {}).items():
        experiments_info.append({
            "name": exp_name,
            "n_features": n_feat,
            "description": exp_descriptions.get(exp_name, ""),
        })

    # Best model string
    best_metrics = summary.get("best_model_metrics", {})
    best_str = ", ".join(
        f"{k}={v:.3f}" for k, v in best_metrics.items()
        if not k.endswith("_std")
    )

    # Class dist string
    class_dist = summary.get("class_distribution", {})
    dist_str = ", ".join(f"{k}: {v}" for k, v in class_dist.items())

    # Statistical tests
    friedman = summary.get("statistical_tests", {}).get("friedman", {})

    # Render
    template = Template(REPORT_TEMPLATE)
    html = template.render(
        title=cfg["report"]["title"],
        author=cfg["report"]["author"],
        primary_metric=cfg["evaluation"]["primary_metric"],
        n_samples=summary.get("n_samples", 0),
        n_features_primary=summary.get("n_features_primary", 0),
        class_labels=cfg["columns"]["class_labels"],
        class_dist_str=dist_str,
        primary_experiment=summary.get("primary_experiment", ""),
        experiments=experiments_info,
        comparison_table_html=table_html,
        figures=figure_map,
        best_model_name=summary.get("best_model_display", ""),
        best_model_metrics_str=best_str,
        friedman_stat=f"{friedman.get('statistic', 'N/A'):.2f}"
            if isinstance(friedman.get("statistic"), (int, float)) else "N/A",
        friedman_p=f"{friedman.get('p_value', 'N/A'):.4f}"
            if isinstance(friedman.get("p_value"), (int, float)) else "N/A",
        significant_findings=summary.get("significant_findings", []),
        n_components_95=summary.get("n_components_95", "N/A"),
        n_splits=cfg["cross_validation"]["n_splits"],
        n_repeats=cfg["cross_validation"]["n_repeats"],
    )

    report_path = Path(cfg["output"]["reports_dir"]) / "classification_report.html"
    report_path.write_text(html, encoding="utf-8")
    print(f"  Saved: {report_path}")

    # JSON summary
    _save_json_summary(summary, cfg)


def _save_json_summary(summary: Dict[str, Any], cfg: Dict[str, Any]) -> None:
    """Save machine-readable JSON summary."""
    json_path = Path(cfg["output"]["reports_dir"]) / "classification_summary.json"

    # Convert non-serialisable objects
    clean = _make_serialisable(summary)
    write_json(str(json_path), clean)
    print(f"  Saved: {json_path}")


def _encode_image(path: Path) -> str:
    """Encode an image file as base64 string."""
    return base64.b64encode(path.read_bytes()).decode("utf-8")


def _make_serialisable(obj: Any) -> Any:
    """Recursively convert numpy/pandas types to native Python."""
    if isinstance(obj, dict):
        return {k: _make_serialisable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_make_serialisable(v) for v in obj]
    if isinstance(obj, pd.DataFrame):
        return obj.to_dict(orient="records")
    if isinstance(obj, pd.Series):
        return obj.to_dict()
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, np.bool_):
        return bool(obj)
    return obj
